name: NotesApp
options:
  bundleIdPrefix: com.piotrlaczkowski
  deploymentTarget:
    iOS: 17.0
    macOS: 14.0
  developmentLanguage: en
  xcodeVersion: "15.0"

packages: {}

targets:
  NotesApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: NotesApp
        excludes:
          - "**/*.plist"
          - "**/NotesDataModel.xcdatamodeld"
    info:
      path: NotesApp/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundleDisplayName: NotesApp
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.piotrlaczkowski.NotesApp
        SWIFT_VERSION: "5.9"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: NotesApp/Info.plist
        ENABLE_PREVIEWS: true
    frameworks:
      - PDFKit
    entitlements:
      path: NotesApp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.piotrlaczkowski.NotesApp
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.yourname.NotesApp

  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
      - path: NotesApp/Models
      - path: NotesApp/Services/ContentExtractor
      - path: NotesApp/Services/LLMEngine
      - path: NotesApp/Utilities
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundleDisplayName: Share to NotesApp
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsWebPageWithMaxCount: 1
              NSExtensionActivationSupportsText: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.NotesApp.ShareExtension
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: ShareExtension/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "Apple Development"
        ENABLE_PREVIEWS: true
    frameworks:
      - PDFKit
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.piotrlaczkowski.NotesApp
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.yourname.NotesApp.ShareExtension


